FROM php:8.3.11-cli

RUN apt-get update

RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y autoconf
RUN apt-get install -y gcc
RUN apt-get install -y make

RUN pecl install grpc

RUN docker-php-ext-enable grpc